### ISSUE TITLE
Add code that can go through every repo in UCSB-CS56-Projects, and every issue, and make a spreadsheet file (.csv) file of every issue

### ISSUE THREAD

**Issue by pconrad** [UCSB-CS56-Projects/cs56-github-apiv3-simple-rest-client#1]
What we want is a a .csv file, that has all the same columns as the existing .csv file created by CS56ProjectList.java BUT instead of just one row (line) per repo, want one line per ISSUE.

And add extra columns, which are issue number, issue status (open/closed), user assigned to, title, description.

estimate: 300 points.

**Comment by jaeaster** [comment]
Issues information can be found at
https://api.github.com/repos/UCSB-CS56-Projects/{repo-name}/issues/{number}

Where {repo-name} is the name of the desired repo
and {number} is the digit # of a particular issue.

The relevant keys are "number", "state", "assignee", "title", "body" (description)

**Comment by jaeaster** [comment]
When accessing the json information for the all the projects in UCSB-CS56-PROJECTS, given here https://api.github.com/orgs/UCSB-CS56-Projects/repos?page=1&per_page=100, each project has a key called "open_issues_count" or "open_issues", which tells you the amount of issues a given project has

**Comment by jaeaster** [comment]
Visiting 

https://api.github.com/repos/UCSB-CS56-Projects/{repo-name}/issues/

will give you all the JSON info for open issues (does not include closed issues)

**Comment by jalexanderqed** [comment]
F16 OK (300 pts)
