### ISSUE TITLE
Add javadoc for all functions and classes

### ISSUE THREAD

**Issue by jalexanderqed** [UCSB-CS56-Projects/cs56-github-apiv3-simple-rest-client#14]
This is particularly important for the utility functions you will create as part of #13. However, all methods, including the specific jobs that can be executed, should have documentation.

**Comment by jalexanderqed** [comment]
F16 OK (150 pts)

**Comment by jaeaster** [comment]
Modified, make javadoc comments for all new code you create as a part of the refactor of this repo!

150 points

**Comment by jaeaster** [comment]
150 awarded
