### ISSUE TITLE
List all members of an organization

### ISSUE THREAD

**Issue by yamen321** [UCSB-CS56-Projects/cs56-github-apiv3-simple-rest-client#5]
For UCSB-CS56-W15 organization, list the github IDs of every member to a file.
It currently only lists 40.

points:75

**Comment by PazZaitGivon** [comment]
looks good

**Comment by jalexanderqed** [comment]
F16 OK (80 pts)

**Comment by jaeaster** [comment]
List all members for the UCSB-CS56-Projects organization

F17 OK (50 points)

**Comment by jaeaster** [comment]
Awarded 50 points
