### ISSUE TITLE
Given a list of github IDs, check whether each one has a W15-lab04  repo

### ISSUE THREAD

**Issue by yamen321** [UCSB-CS56-Projects/cs56-github-apiv3-simple-rest-client#6]
For each one, write to a file Yes or No whether the repo exists. If it does exist, write the URL of the repo.

points:200

**Comment by PazZaitGivon** [comment]
looks good

**Comment by jalexanderqed** [comment]
Make the searched repository name (e.g. "W15-lab05") configurable so that this can be used for any quarter or project.

**Comment by jalexanderqed** [comment]
F16 OK (200 pts)
