### ISSUE TITLE
Add on to issue one, one more level of nesting that iterates through the comments

### ISSUE THREAD

**Issue by yamen321** [UCSB-CS56-Projects/cs56-github-apiv3-simple-rest-client#7]
In #1  we are making the .csv file every line should be a separate issue of every project repo. 
In this issue, make it so that every line has another line that has all the issue comments. (Find a way to differentiate the comments so that they don't look like the rest of the issue and that you know which issue they belong to. i.e. comment number or white space).

points: 200

**Comment by PazZaitGivon** [comment]
looks good

**Comment by jalexanderqed** [comment]
F16 OK (150 pts)
